# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c06b057fb9e9e40efcdf55ef42a73043d0812ee0cd7c88320b146557d67a63367f65806cf273acfac6b51b3b1936b47a8fcd1138a457383381568e7a77bde614

test:
  secret_key_base: 83f8c1cf7916e40f5e934b51b60e86493823cf728aa8a894f9dc86da151edd614efd71fe2d1f70270689d30515be43fea0cdbb4d2e644a2f0893f7d2395d6a47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
